# .github/workflows/ml.yml
name: ML CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas scikit-learn joblib

    - name: Run ML pipeline
      run: python main.py
